### ISSUE TITLE
Resources not found.

### ISSUE THREAD

**Issue by N4tus** [IGI-111/freecell#1] opened 2021-08-19 11:05 UTC
When compiling with `RUSTFLAGS='-C target-cpu=native' cargo build --release` the resulting binary panics with:  
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
ResourceNotFound("/cards.png", [
("~/games/freecell/target/release/resources", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })),
("~/.local/share/freecell", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })), 
("~/.config/freecell", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })), 
("./resources", IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
])',
src/game.rs:41:61
```

**Comment by IGI-111** [comment] 2021-08-19 12:08
Tried a clean build but I can't reproduce.
What OS and architecture are you running?

**Comment by N4tus** [comment] 2021-08-19 22:09
the thing is, that the binary has to be executed next to the "resources" folder. When using a `cargo build` the binary is not located there. Is is possible to include the resources in the binary? Copying both together works but it would just be nice to have one binary that includes all.

**Comment by IGI-111** [comment] 2021-08-19 22:15
Unfortunately, that's [how ggez works](https://github.com/ggez/ggez/blob/master/docs/FAQ.md#errors_resource), there is a trick to add the Cargo manifest path to build and run ([see here]( https://github.com/IGI-111/freecell/blob/08aec4a4d3324c4f30ada60d02c51dbaf8fdb7de/src/main.rs#L18)) but I haven't found a way to embed the ressources in the binary so far.

Closing since this is working as intended.

**Closed as completed by IGI-111** 2021-08-19 22:15 UTC
